# Generated by Django 6.0.4 on 2026-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='requests/')),
                ('source', models.CharField(choices=[('site', 'Site'), ('bot', 'Telegram Bot')], default='site', max_length=10)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('offered', 'Offered'), ('paid', 'Paid'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='new', max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('family', 'Family'), ('criminal', 'Criminal'), ('labor', 'Labor'), ('tax', 'Tax'), ('contract', 'Contract'), ('other', 'Other')], max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('admin_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='contact_req_date_82cc20_idx'), models.Index(fields=['status'], name='contact_req_status_1f80e7_idx')],
            },
        ),
    ]
